language: dart
dart:
  - dev

# Build stages: https://docs.travis-ci.com/user/build-stages/.
stages:
  - analyze_and_format
  - testing
  - prepub
  - deploy

jobs:
  include:
    - stage: analyze_and_format
      name: "Check with dartanalyzer and dartfmt"
      script: ./tool/travis/swag.sh

    - stage: testing
      name: "Unit tests"
      script: pub run test
    
    - stage: prepub
      name: "Prepublish checks"
      script: pub publish --dry-run
      
    - stage: deploy
      name: "Deploy on pub.dartlang.org"
      if: ((tag =~ ^v) AND (branch = master))
      deploy:
        provider: script
        script: ./tool/travis/pub.sh
        on:
          branch: master

branches:
  only: [master, develop]

# Incremental pub cache and builds.
cache:
  directories:
    - $HOME/.pub-cache
