name: dart_lut
version: 0.0.4+hotfix.1
description: The implementation of image processing via 3D LUT (LookUp Tables). It's written on the pure Dart language so that it can be used with Flutter, CLI and web.
homepage: https://github.com/NiKoTron/dart-lut

environment:
  sdk: ^3.5.3

dependencies:
  meta: ^1.16.0

dev_dependencies:
  test: ^1.25.8
  lints: ^5.0.0
  image: ^4.3.0
  args: ^2.6.0
  path: ^1.9.1
  