name: dart_lut
version: 0.0.4+hotfix.1
description: The implementation of image processing via 3D LUT (LookUp Tables). It's written on the pure Dart language so that it can be used with Flutter, CLI and web.
author: Nikolai Simonov <nickolay.simonov@gmail.com>
homepage: https://github.com/NiKoTron/dart-lut

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
  image: ^2.0.4
  args: ^1.5.1
  path: ^1.6.2
  